//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemChung.models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("HoaDonThanhToan")]
    public partial class HoaDonThanhToan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonThanhToan()
        {
            this.XacNhanThanhToans = new HashSet<XacNhanThanhToan>();
        }
        [Key]
        public string MaHDTT { get; set; }
        public string MaPDK { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string LoaiThanhToan { get; set; }
        public Nullable<int> SoDotThanhToan { get; set; }
        public Nullable<System.DateTime> NgayThanhToanTiepTheo { get; set; }
        public Nullable<double> ThanhTienMoiDot { get; set; }
        public string PhuongThucGuiTien { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<double> TongTienDaThanhToan { get; set; }
        public string KhachHang { get; set; }
    
        public virtual KhachHang KhachHang1 { get; set; }
        public virtual PhieuDangKy PhieuDangKy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XacNhanThanhToan> XacNhanThanhToans { get; set; }
    }
}
