//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemChung.models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("LichRanh")]
    public partial class LichRanh
    {
        [Key]
        public string MaNV { get; set; }
        public System.DateTime Ngay { get; set; }
        public string Ca { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
