//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemChung.models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("PhieuDangKy")]
    public partial class PhieuDangKy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuDangKy()
        {
            this.HoaDonThanhToans = new HashSet<HoaDonThanhToan>();
        }
        [Key]
        public string MaPDK { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string GoiVaccine { get; set; }
        public Nullable<System.DateTime> NgayTiem { get; set; }
        public string NVGhiNhan { get; set; }
        public string MaKH { get; set; }
        public string Them { get; set; }
        public virtual DanhSachCacGoiTiem DanhSachCacGoiTiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonThanhToan> HoaDonThanhToans { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
