//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemChung.models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TreEm")]
    public partial class TreEm
    {
        [Key]
        [ForeignKey("KhachHang")]
        public string MaKH { get; set; }
        public string HoTenNguoiGiamHo { get; set; }
        public string QuanHe { get; set; }
        public string SDTNguoiGiamHo { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
