//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemChung.models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("XacNhanThanhToan")]
    public partial class XacNhanThanhToan
    {
        [Key]
        public string MaXNTT { get; set; }
        public string MaHDTT { get; set; }

        //public string Them { get; set; }
        public Nullable<int> DotThanhToan { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<System.DateTime> NgayThanhToanTiepTheo { get; set; }
        public Nullable<double> TongTienChuaTT { get; set; }
    
        public virtual HoaDonThanhToan HoaDonThanhToan { get; set; }
    }
}
